export const exercises = [
  { description: "Skipping", time: 60 },
  { description: "Jumping jacks", time: 60 },
  { description: "Foot fire", time: 30 },
  { description: "High knees", time: 30 },
  { description: "Rest...", time: 60 },
  { description: "Skipping", time: 60 },
  { description: "Jumping jacks", time: 60 },
  { description: "Foot fires", time: 30 },
  { description: "High knees", time: 30 },
  { description: "Rest...", time: 90 },
  { description: "10 Pushups", time: 30 },
  { description: "Mountain climbers", time: 30 },
  { description: "15 squats", time: 40 },
  { description: "Rest...", time: 60 },
  { description: "10 Sprawls", time: 50 },
  { description: "Speed punches", time: 30 },
  { description: "5 Pullups", time: 40 },
  { description: "Rest...", time: 60 },
  { description: "Mountain clibers", time: 30 },
  { description: "10 Pushups", time: 30 },
  { description: "Squat hold", time: 30 },
  { description: "Rest...", time: 60 },
  { description: "Flutter kick", time: 30 },
  { description: "15 squats", time: 40 },
  { description: "Pushup hold", time: 30 },
  { description: "Rest...", time: 60 },
  { description: "Squat hold", time: 30 },
  { description: "5 Pullups", time: 40 },
  { description: "Pushup hold", time: 30 },
  { description: "Rest...", time: 60 },
  { description: "10 Burpees", time: 60 },
  { description: "Speed punches", time: 30 },
  { description: "Plank", time: 60 },
  { description: "Scissors", time: 30 },
  { description: "Rest...", time: 90 },
  { description: "Child pose", time: 30 },
  { description: "Pigeon stretch - left", time: 30 },
  { description: "Pigeon stretch - right", time: 30 },
  { description: "Shoulder stretch - left", time: 15 },
  { description: "Shoulder stretch - right", time: 15 },
  { description: "Triceps stretch - left", time: 15 },
  { description: "Triceps stretch - right", time: 15 },
  { description: "Chest stretch", time: 30 },
  { description: "Back stretch", time: 30 },
  { description: "Hamstring stretch - left", time: 15 },
  { description: "Hamstring stretch - right", time: 15 },
];